project_id = "logistical-dumpster"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:19006"

[storage]
enabled = true
file_size_limit = "50MiB"

[functions.notify]
verify_jwt = true

[functions.submit-claim]
verify_jwt = true

[functions.review-claim]
verify_jwt = true

[functions.claim-lifecycle]
verify_jwt = false
